services:
  - type: web
    name: my-go-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: "go build -o main ."
    startCommand: "./main"
    port: 8080
    plan: free
  - type: web
    name: rabbitmq
    env: docker
    dockerfilePath: ./Dockerfile-rabbitmq
    plan: free